### ISSUE TITLE
Exporting folder rules

### ISSUE THREAD

**Issue by billydekid** [vprince1/alfresco-bulk-export#2]
Hi,
Thanks for this great tool.
I have a requirement to export our developed folder with its rules to production server.
Do you have a plan to add this feature, or any clue to solve this?

Thank you,

**Comment by vprince1** [comment]
Thanks for you email Bayu… I am not planning to add this feature currently. The main reason is because, the output of this tool is supposed to work as the input for the Alfresco Bulk Import tool by pmonks. Since his tool does not process the folder rules, i have no current plans to add this. You can solve this is many different ways. It really depends on how complicated and how re-usable you want your solution to be. If you only plan on using it once in your environment and you also know all the different rule names, you should be able to just append an aspect that is specific to a rule on the folder object. After you import into your new environment, you can write some custom code that will located these unique aspects then will add the rule programmatically.

If you want to make it more generic, then I would think you will have to come up with you own XML tag structure and also modify bulk import to process these new tags.

HTH,
Vijay

**Comment by billydekid** [comment]
Thank you Vijay for your suggestions by creating custom XML. 

I also posted this on alfresco forum https://community.alfresco.com/thread/238261-how-to-export-folder-with-its-rules

Thank you,
